name: Publish Nuget

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-rc**"

env:
  DOTNET_VERSION: '3.1.417'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --configuration Debug /p:Version=${VERSION}

    - name: Test
      run: dotnet test --configuration Debug /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack --configuration Debug /p:Version=${VERSION} --no-build --output .

    - name: Push
      run: dotnet nuget push SourceLink.Demo.Library.${VERSION}.nupkg --source https://nuget.pkg.github.com/picardh-cision/index.json --api-key ${GITHUB_TOKEN}
